#!/usr/bin/env node
// GitNexus can't parse inline <script> JS inside index.html — the entire game.
// This emits tools/index-inline.mirror.part<N>.js files: each is the SAME length/
// newlines as index.html with every character blanked to a space EXCEPT that part's
// slice of the inline JS, so graph anchors citing any part's line N refer to
// index.html line N — same line number, read/edit index.html there.
// Parts exist because the indexer's per-file parse budget times out on one huge
// mirror (~>600KB live code); each part carries <=MAX_PART_CHARS of live code and
// splits only at column-0 top-level statement boundaries (validated by node --check).
// Regenerate + re-index after ANY index.html edit:
//   node tools/extract-inline.mjs && npx gitnexus analyze
// Never edit the mirrors, never load them from the page.
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const MAX_PART_CHARS = 250000; // live-code chars per part — comfortably inside the parser budget

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'index.html'), 'utf8');

// Blank everything (newlines preserved, UTF-16 code units so regex offsets align),
// then copy inline-JS spans back verbatim.
const blank = src.split('').map(ch => (ch === '\n' || ch === '\r') ? ch : ' ');
const spans = []; // [startOffset, endOffset) of inline JS in src
const drop = []; // token ranges blanked from the mirror (IIFE wrappers that would straddle parts)
const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
let m, jsChars = 0;
while ((m = re.exec(src)) !== null) {
  if (/\bsrc\s*=/i.test(m[1])) continue;
  const start = m.index + m[0].indexOf('>') + 1;
  spans.push([start, start + m[2].length]);
  jsChars += m[2].length;
  // A span wrapped in `(function(){ ... })();` can't be split across parts (opener
  // and closer would land in different files) — blank the wrapper tokens so the body
  // parses as top-level statements. Scoping loss is irrelevant to a parse-only mirror.
  const open = /^\s*\(function\s*\(\s*\)\s*\{/.exec(m[2]);
  const close = /\}\s*\)\s*\(\s*\)\s*;?\s*$/.exec(m[2]);
  if (open && close) {
    drop.push([start + open.index, start + open.index + open[0].length]);
    drop.push([start + close.index, start + close.index + close[0].length]);
  }
}

// Line-start offsets, and per-line live-code char counts.
const lineStart = [0];
for (let i = 0; i < src.length; i++) if (src[i] === '\n') lineStart.push(i + 1);
const lineOfOffset = off => {
  let lo = 0, hi = lineStart.length - 1;
  while (lo < hi) { const mid = (lo + hi + 1) >> 1; if (lineStart[mid] <= off) lo = mid; else hi = mid - 1; }
  return lo;
};

// Candidate split lines: column-0 top-level statement starts inside JS spans.
const lines = src.split('\n');
const isCandidate = ln => /^(function |const |let |var |\/\* )/.test(lines[ln] || '');

// Greedy partition: accumulate live chars per line; when a part exceeds the cap,
// cut at the most recent candidate line.
const liveOnLine = new Array(lines.length).fill(0);
for (const [s, e] of spans) {
  let ln = lineOfOffset(s);
  let pos = s;
  while (pos < e) {
    const lineEnd = ln + 1 < lineStart.length ? lineStart[ln + 1] : src.length;
    liveOnLine[ln] += Math.min(e, lineEnd) - pos;
    pos = Math.min(e, lineEnd);
    ln++;
  }
}
const cuts = []; // first line of each new part (part 0 starts at 0)
let acc = 0, lastCand = -1;
for (let ln = 0; ln < lines.length; ln++) {
  if (isCandidate(ln)) lastCand = ln;
  acc += liveOnLine[ln];
  if (acc > MAX_PART_CHARS && lastCand > (cuts[cuts.length - 1] ?? 0)) {
    cuts.push(lastCand);
    acc = 0;
    for (let k = lastCand; k <= ln; k++) acc += liveOnLine[k];
    lastCand = -1;
  }
}
const partStarts = [0, ...cuts];
const partCount = partStarts.length;

// Remove stale mirror files (old single-file name included).
for (const f of readdirSync(join(root, 'tools'))) {
  if (/^index-inline\.mirror(\.part\d+)?\.js$/.test(f)) unlinkSync(join(root, 'tools', f));
}

const banner = pi => `// GENERATED by tools/extract-inline.mjs — line-preserving JS mirror of index.html inline scripts, part ${pi + 1}/${partCount}. Line N here = index.html line N. Do not edit.`;
for (let pi = 0; pi < partCount; pi++) {
  const from = lineStart[partStarts[pi]];
  const to = pi + 1 < partCount ? lineStart[partStarts[pi + 1]] : src.length;
  const out = blank.slice();
  for (const [s, e] of spans) {
    const a = Math.max(s, from), b = Math.min(e, to);
    for (let i = a; i < b; i++) out[i] = src[i];
  }
  for (const [s, e] of drop) {
    const a = Math.max(s, from), b = Math.min(e, to);
    for (let i = a; i < b; i++) { const ch = out[i]; if (ch !== '\n' && ch !== '\r') out[i] = ' '; }
  }
  let text = out.join('');
  const nl = text.indexOf('\n');
  const line1 = text.slice(0, nl);
  text = (line1.trim() === '' ? banner(pi) : line1) + text.slice(nl);
  writeFileSync(join(root, 'tools', `index-inline.mirror.part${pi + 1}.js`), text);
}
console.log(`mirror: ${spans.length} inline script blocks, ${jsChars} JS chars, ${partCount} part(s), lines 1:1 with index.html`);
