#!/usr/bin/env node
// GitNexus can't parse inline <script> JS inside index.html — the entire game.
// This emits tools/index-inline.mirror.js: identical length/newlines to index.html
// with every non-inline-JS character blanked to a space, so the knowledge graph's
// file:line (and column) anchors map 1:1 onto index.html. Regenerate + re-index:
//   node tools/extract-inline.mjs && npx gitnexus analyze
// The mirror is generated — never edit it, never load it from the page.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'index.html'), 'utf8');

// Start fully blanked (newlines preserved), then copy inline-JS spans back verbatim.
// split('') = UTF-16 code units, matching regex .index offsets (Array.from iterates
// code points and would skew every offset after the first emoji in the file).
const out = src.split('').map(ch => (ch === '\n' || ch === '\r') ? ch : ' ');
const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
let m, blocks = 0, jsChars = 0;
while ((m = re.exec(src)) !== null) {
  if (/\bsrc\s*=/i.test(m[1])) continue; // external script — nothing inline to mirror
  const start = m.index + m[0].indexOf('>') + 1;
  for (let i = 0; i < m[2].length; i++) out[start + i] = m[2][i];
  blocks++; jsChars += m[2].length;
}
// Banner goes on line 1 (markup in index.html, so its mirror slot is blank) — line numbers stay 1:1.
const text = out.join('');
const nl = text.indexOf('\n');
const banner = '// GENERATED by tools/extract-inline.mjs — line-preserving JS mirror of index.html inline scripts. Do not edit.';
const line1 = text.slice(0, nl);
const merged = (line1.trim() === '' ? banner : line1) + text.slice(nl);
writeFileSync(join(root, 'tools', 'index-inline.mirror.js'), merged);
console.log(`mirror: ${blocks} inline script blocks, ${jsChars} JS chars, lines 1:1 with index.html`);
