// GENERATED by tools/extract-inline.mjs — line-preserving JS mirror of index.html inline scripts, part 1/1. Line N here = index.html line N. Do not edit.
                
      
                        
                                                                                          
                                               
                                                                                                                                                                                                     
                                           
        document.documentElement.classList.add('i18n-pending');var LANG=/(?:^|[?&#])en\b/.test(location.search+location.hash)?'en':/(?:^|[?&#])ja\b/.test(location.search+location.hash)?'ja':(/^ja/i.test((navigator.languages&&navigator.languages[0])||navigator.language||'')?'ja':'en');document.documentElement.lang=LANG;if(LANG==='ja')document.title='月の合唱 — リズムエイム・トレーナー';try{if(localStorage.getItem('aimdojo.seen'))document.documentElement.classList.add('seen')}catch(e){}                                                                                                           
                                           
                                                                     
                                                                                                                                                                                                            
                                            
                                                                      
                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                  
                                                           
                                                                    
                                                                                                    
       
      
                                                                            
                                                                                      
                                     
                                                                                                 
                                                                          
                                                                            
                                                                                                                                                
 
                        
                                                                                                                                                   
                                                                                                        

                                                                                                                                                                                                 
                                             
                                                                                                                                  

                                                                                                                             
                                                                                                 
                                                          
                                                          
                                                             
                                                               
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                     
                                                                                                                      
                                
                                                                                                                                                                                                                                     
                                                             
                                                                                                                                                                    
                                                                                                                    
                                                                                                                          
                                                                    
                                                                                                                                                                       
                                                                                                         
                                                                                                                                                                                                                                      
                          
                                                                                 
                                                                                                        
                                           
                                              
                                             
                                                                                        
                                                                                                                                                                                                                                                                                                   
                                                       
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                              
                                                                                                                          
                           
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    
                            
                                                                                                                                                                                                                                                                                                  
                          
                                                                                                                            
                                                                                                                                                                                                 
                               
                                                                                                                           
                                                                           
                                            
                                                  
                                                                                                                                                                                                                                                                                               
                                                                                                         
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                
                         
                                                                                                                                                   
                                         
                                                    
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                          
                         
                                                                                              
                          
                                                                                                                                                                             
                      
                                                                                             
                                                                                            
                                                                                                                                                                                                  
                                                                                                                                       
                                                                                                                               
                                                                                        
                                                                                         
                                                                                         
                                                                                          
                                                                                                                                   
                                                      

                                                                                                                                 
                                               
                                                                                    
                                                                                                
                                                                                                                                       
                                               
                                                                                                              
                                                                                                                                                   

                                                             
                                                                         
                                                                                                                                                                                                                                                                                                               

                                                                                     

                                               
                                                                     
                                                                                           
                                                                  
                                             
                                                 
                                                                                                            
                                                                                                             


                                                                                                                                                                                                                                             
                                                           

                                                 
                                                                         
                          
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
                                                                     
                                                                                                                                                                                                                       
                                                             

                                                                                                
                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                 
                                                                              
                                                                      
                               
                                                                              
                          
                                                                                                                                                                                       
                                                                                                            
                               
                                                                                           
                                                                                                                                     
                                                                                                     
                                                                                                                                                                                                 
                                                                                                                                                                                                                                                
                                            
                                                    
                                                                     
                                                                                                                                                                                                                                                                            
                                                                              
                                                                                                                                                
                         
                                                                                                    
                                                                             
                                         
                                                                                                                
                                       
                                     
                                                      
                                        
                                                       
                                       
                                         
                                      
                                         
                                                                                                                                
                                                     
                                                                                                                                                   
                                                                      
                                                                                                                                                                                                                                                                                                                                                                        
                         

                                                                                                      
                                                                                                          
                                                                                    
                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                
                                                                                                                   
                                       
                                                                         
                                        
                                                                                       
                                                                                            
                                        
                                                        
                                            
                                             
                                                                                                       
                                                                                                                                                                                                 
                                                                           
                                        
                                                                                    
                                                                                                                                                                                                    
                                                                                   
                                                                                                                     
                                                       
                                                                                    
                                                                                                  
                                                                                                                                                                                                                              
                                    
                                                                                                                    
                                                                                
                                                                                                                                                                                                                                                                 
                                                                                                                                                                                        
                                                                                                                                                                                        
                                                                                                                                        
                                                                                                                                                                                             
                                                                                
                                                                                    
                                                            
                                                                                                                               
                                                                                                        
                                                                                                                                                                                         
                                                                                                       
                                            
                                                                                                                                                                                              
                                                              
                                                                                                     
                                                                  
                                                                                                                                                                                                                                                                                
                                                                                                                            
                                                         
                                                                                                                                                                                                                                                                                                               

                                                                                                   
                                  
                                            
                                                              
                                                                                                                                                                                                                                                                             
                                                   
                                                                                              

                                                                                                                                                                 
                                                                                                                                                                                                                          
                                                         
                                                                                                                                                                                                                                                                                                                                                    
                            
                                         
                                                                                                                                                                                                                     

                                                                   
                                        
                                                                                                                    
                                                                    
                                                          
                                                                         
                                                                                                   
                                                                                                                                                                                            
                                                                  
                                                                                                    
                                                                                                                           
                                                            
                                                                                     
                                                               
                                                                                     
                                             
                                                              
                                                                                                        
                                                                                                                                                               
                                                                   
                                                                     
                                                                
                                                                                                                                                                            
                            
                                                                         
                                                                                                                                                                                                                            
                                                                      
                                                                                    
                                                                                             
                                                                                          
                                                                      
                                                     
                                                     
                                                                                                                                                                                                                                                                
                                                           
                                                                                                                                                                                                                                                                                            
                                                                        
                                                                                                                                                                      

                           
                                                                                                                                                                                                                      
                                  
                              
                                    
                                                                                                                                                                                                                                                      
                                                                                    
                                                
                                                                                                                                                                                          
                                                                        
                                                  
                                                                                            

                                                                           
                                                                           
                                                                                                         
                                                                          
                                                                                                                
                                                                                                                                                                                                                         
                                        
                                      
                                                                                                         
                                                                                                                                                     
                                 
                                                    
                                                                                                                                                                                                       
                                      
                                                                                       
                                                           
                                                          
                                                                                                                  
                                        
                                                                                                                  
                                                                                     
                                                                                                  
                                                                                                                    
                                                                                                                      
                                                                                                                                         
                                                                                                                                                                              
                                                                                                         
                                                                                                  
                                                                  
                                                                                                                                    
                                                   
                                                                                                                                                                                         
                                                            
                                                                                       
                                                                                                                                         
                           
                                                   
                                                                                                                                          
                                                                                                               
                                                                                 
                                                                                                                                 
                                      
                                                                                                                                                                                      
                                                
                                                                                                                       
                                                               
                                                                                                                               
                                                                   
                                                                     
                                                                    
                                                                                                
                                     
                                                                 
                                                                                                                                           
                                                                
                                                                                                                                    
                                                   
                                                                                                    
                               
                                                                                   
                                                                                                           
                                                         
                                                                                                                          
                                                                                                     
                                
                                                                                                           
                                                                         
                                                                                              
                                                                                                                                                                                                                                                                                                        
                                                                                                   
                                        
                                                                      
                                                                                                              
                                                                  
                                                                                                                         
                                        
                                            
                                         
                                                                               
                                              
                                                                                                          
                                                                       
                                                                                                                                                                                                                                         
                                        
                                                                                                                       
                                                                                                                
                                                                                          
                                                                                                                                  
                                      
                                                                                             
                                                                                                    
                                                                                               
                                          
                                                                                                                                                                            
                                                             
                                              
                                                                                                                                                                                                                                       
        
                                                                                                                                                                                                
       
      
                            
                                             
                                            
                                       
                                     
                                                        
                                                        
                         
                                                  
      
                                              
                                                                      
                                                
                                              
      
                                                        
                                           
                                                                                                                                                                       
                                                                          
                                                                             
                                             
                                                                                                      
                                                                                               
                                                                                                         
                                          

                                            
                                             

                               
                                 
                                                       
      

                                                                              
                                              
                                                                               
                                                                      
                                                                                                                     
                                                          
                                                                                                                                           
                                                                                                                                                                                
        
                                                          
                                                        
                                                        
                                                                                              
                                                                                                                                                               
                                                                                                                
                                                                                                                                    
                                                                                                          
                                                                                   
                                                                                                                                                                                                         
                                                                                               
             
                                                                                                                                                                                                                                 
          
            
        

                
                                                      
                                                               
      

                  
                    
                                                                
                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                           

                                   
                                                                     
                                                                                                       
                                                                                             
                                                                                     
                                                                     
                                                                                                       
                                                                                                         
                                                                                                                  
                                                                                                   
          
                                              
                                    
                                                       
                                                            
                                                                
                                             
          

                                                    
                                                                                 
                                                                                                                           
                                                                      
                                                                                                                                                                              
                                                                                                                                                                        
                                                                                                                                                                                
                                                                                                                                                                            
            
                                                                                                                                  
                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                  
                                                                                                      
            
                                                                                                                                   
                                                                                                                                                                                                                                   
                                                                                                                                                   
                                                                                                                                                                                                          
                                                 
                                                                                                                                                                    
                                                  
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                      
                                                                                                                     
                  
                
                                                                                                                                                   
                  
            
                                                                                                                                         
                                                                                                            
                                                  
                                                                         
                                                                                                                     
                                                        
                                                                                                      
                                                                                                                                                                                               
                    
                                                                                                                                                               
                 
                                              
                                                                                                                                                                                                
                                                                                                              
                                                                     
                                                                                
                                            
                                                                                                                           
                                                                                                                        
                    
                  
                                      
                                                                                                          
                                           
                                                                                                                                                                    
                                                                                                                                                                    
                      
                                                                                                                                                                        
                                           
                                                                                                              
                                                                                                        
                                                                
                             
                          
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
                      
                                              
                                                                                                                                 
                                                                                                                                
                                                                                                                                            
                      
                     
                  
                
                                                                                                                                                 
                                                                                                 
              
                                                            
                                                                                                                                                                                                                          
                                                                                                      
              
                                                                                                                                
                                                                                                                                                                                                               
                                         
                                                                                                                                   
                                                                                                                                                                   
                
                                                                                                                                                                    
                                                                                                                                         
                  
            
                                                                                                                                                                                             
                                                                                                                                      
                                
                                                                   
                                                   
                                                                                                    
                                                                                        
                                                                                                                    
               
              
                                
                                                                          
                                                   
                                                                                                                                 
                                                                                              
                                                                                                                                                                        
               
              
                                
                                                                        
                                                  
                                                                                                                                                                    
                                                                                                                                 
               
              
                                
                                                             
                                                 
                                                                                           
                                                                                                                                                                    
                                                                                                                                                                                                                       
                                                                                                                            
               
              
                                
                                                                       
                                                 
                                                                                                                                                                                                         
                                                                                                   
                                                                             
               
              
                                
                                                           
                                                  
                                              
                                                                                 
                                                                        
                                                                     
                                                                                       
                                                
                                                                                               
                                                                      
               
              
                                
                                                                   
                                                    
                                                                                                    
                                                                           
                                                                              
                                                                             
                                                           
                                                                   
                                                                                                             
               
              
                                
                                                             
                                                   
                                                     
                                                                
                                                                            
                                                                                            
               
              
            
          

                                                                                             
                       
                                                            
                                                                                                                                                                          
          
                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                           

                                                               
                                         
                                                                                                                                                                                                                                                                 
                                             
                                                                                                          
              
                                                                                                            
                                                                                                            
                                                                                                                                                                                                                                                   
            
          

                                                                                                                                                                                          
                                                                 
                            
                                                                                                                 
                                                                                                                                                                                                                                                                                                                                  
                                                                                        
            
          
        
      

                                                                                                                         
                                                         
                                                                          
                                                     
                                                                  
                                                                      
                                                                                    
                                                            
                                                  
              
                                                                                                                            
                                                                                                                                                                                                                     
            
      

                                      
                               
                                                                                                 
                                                                     
                                                                                                                                                                             
                                                                                
                           
                                                                            
                                                      
          
                                                                              
                                                                                                                                                 
        
      

        
/* English lives at each surface; Japanese is the one flat display-only override table. */
window.JA={
  title:'月の合唱 — リズムエイム・トレーナー',
  eyebrow:'月の失われた合唱', titleHtml:'月の<span class="acc">合唱</span>',
  ledeFirstHtml:'恐竜より昔、月は 出会ったすべての心の声で ひとつの歌を守っていた。やがて「大いなる沈黙」が、その声たちを閉じた《こだま玉》にとじこめ、地球じゅうに散らした。きみは新しい「きき手」。<b>床が光ったら、見えている文字を踏んで</b>、月の糸をととのえよう。<b>あいだにリンクを送って</b>、玉が光るあいだに届けよう。失われた声を、家へ。',
  ledeReturn:'床が光ったら踏む。送る。光る時に届ける。',
  ledeMobileHtml:'虹のリンクを早めに送って、こだまが光るあいだに届けよう。れんしゅうは近くのこだまから。',
  phones:'ヘッドホンがおすすめ。世界の太鼓は耳の中に。音を出してね。',
  mouseDesc:'視点 / ねらい', wasdDesc:'床が光ったら 見えている文字を押す',
  clickDesc:'発射 — こだまが光るうちに届ける', freezeDesc:'空のノートを閉じる（道場）', escDesc:'ポーズ / 再開',
  selectDesc:'照準下の空の対象に印をつける', templeEDesc:'印あり: 神殿に入る · 神殿内: 出る', templeFreeDesc:'神殿内: マウス解放（視点はそのまま）· HUD操作', templeTDesc:'神殿内: 空にたずねる（チャート保存が必要）',
  beatCircleLabel:'ビートの輪', beatCircleOn:'ON ▸ タップでOFF', beatCircleOff:'OFF ▸ タップでON', beatCircleHintOn:'けいこの輪を表示', beatCircleHintOff:'けいこの輪を隠す',
  modeQ:'夜が まっている', beginTrain:'はじめる — 月の糸をおしえて', resume:'つづける', resumeWait:'すこしまって…', konamiToastNow:'月のせんせいは よそみ中 · まんげつの夜へ', konamiTeach:'せんせいのひみつ · W W S S A D A D · 左 · スペース — つぎは じゅぎょうをとばせる',
  records:'きろく', share:'シェア', drum:'太鼓', send:'送る', sendAria:'リンクを送る', pauseAria:'ポーズ', muteAria:'音の切りかえ',
  resolution:'画質', offset:'音のずれ', calibrate:'タップから自動調整',
  skyNaturalOn:'NATURAL ▸ タップでTHEATRE', skyTheatreOn:'THEATRE ▸ タップでNATURAL', skyNaturalHint:'現在地の実時間の空 · フリーズなし', skyTheatreHint:'数分で空が一周 · 右クリックでフリーズ',
  playSettingsSummary:'あそび', skySettingsSummary:'そら', chartSettingsSummary:'わたしのチャート', helpSettingsSummary:'ヘルプ',
  helpVerbsTitle:'みっつの うごき', helpNightTitle:'夜の いき', helpTankTitle:'おおきな こだま', helpSkyTitle:'ほしぞら', helpBowTitle:'夜のおわり',
  helpDojoTitle:'道場', helpTempleTitle:'空の神殿', helpChartTitle:'チャート',
  // HELP tab: each list is swapped WHOLE (innerHTML) — keycaps and button names stay Latin, per the stats/keys principle
  helpVerbsHtml:'<li><b>ふむ</b> — 床が光ったら その文字を押す。月の糸が ととのう。</li><li><b>送る</b> — ビートの<b>あいだ</b>でリンクをはなす。ビートの上ではない。</li><li><b>とどける</b> — <b>とどいた しゅんかん</b>で きまる。指をはなした時ではない。遠い声ほど 早めに送る。</li>',
  helpNightHtml:'<li>こだまは 波のように やってきて、そのあと 1小節だけ お休み。新しい声は来ず 合唱がふくらむ。そこで いきをつく。</li><li>世界の太鼓は 波の切れ目でしか はやさを変えない — きみの手の下では 変わらない。</li><li>きれいに とどけつづけると チクタクが うすくなって 1拍めだけになる。はずすと そっと もどる。しずかなのは きみが じぶんで 拍をきざんでいる しるし。</li>',
  helpTankHtml:'<li>波のおわりに 出てくる。れんだではなく かたち — 光る順に <b>3</b>、<b>4</b>、そして お休みをひらく <b>1</b> にとどける。</li><li>かたちを はずしても へるものはない。見送っても そのまま 帰っていく。</li>',
  helpSkyHtml:'<li>こだまは みんな いま空に出ている ほんとうの星の方角から よんでいる。</li><li>とどけた声は つぎの あいだに 星へ帰り、その星は きみの空で ずっと明るくなる。明るい星は きみが もどってきた夜に うたってくれる。</li><li><b>E をおしたまま</b> 何もない空へ送ると 星に印がつく。もういちど <b>E</b> で 空の神殿へ。こだまが前にいるときは 道場がそう教えて、リンクは こだまへ とんでいく。</li><li>月が その夜のきまりを くばる。しきいで 一行だけ 名前を告げる。せっていは いらない。</li>',
  helpBowHtml:'<li>十すうびょう 送らず 踏まずにいると 夜が おじぎをする — のこったこだまが 空へのぼり、太鼓がゆるんで とけ、きみのタイミングの紋がひとつ、そして ほんとうの一行。</li><li>そのさいしょの ひといきで 気が変わったら、なにも失わずに つづきへ もどれる。</li><li>おじぎのあとは 戸口で <b>NIGHT CARD</b> が まっている。</li>',
  helpDojoHtml:'<li><b>MOUSE</b> — 視点 / ねらい</li><li><b>WASD</b> — 床が光ったら 見えている文字を押す</li><li><b>L-CLICK</b> — 送る。こだまが光るうちに とどける</li><li><b>SEND</b>（タッチ）— 同じリンク。ドラッグでねらう</li><li><b>R-CLICK</b> — 空のノートを閉じる（THEATRE では 空をとめる）</li><li><b>ESC</b> — ポーズ / 再開</li><li><b>HOLD E + FIRE</b> — 照準下の空の対象に印をつける（金色に光る）</li><li><b>E</b>（印のあと もういちど）— 空の神殿に入る</li>',
  helpTempleHtml:'<li><b>入る</b> — 道場から: <b>HOLD E + FIRE</b> で印、そして もういちど <b>E</b></li><li><b>FIRE</b> — 照準下の対象をしらべる</li><li><b>SHIFT+E</b> — パネル用にマウス解放。視点はそのまま</li><li><b>T</b> — 空にたずねる（CHART でチャート保存が必要）</li><li><b>E</b> — 神殿を出る（道場へ）</li><li><b>ESC</b> — ポーズ（再開で神殿にもどる）</li><li>八つの月の輪は きみが遊んだ夜の 月のかたち。ふえるだけ。</li>',
  helpChartHtml:'<li>任意。なくても遊べる。</li><li>CHART でサインイン → 出生チャートを ひとつ保存。</li><li>神殿の <b>T</b>（質問）と 今日の空のノートが つかえるようになる。</li><li>保存すると 入力欄は たたまれる。<b>EDIT CHART</b> か <b>NEW CHART</b> を使ってね。</li>',
  observerLocation:'場所', observerGeo:'現在地を使う', observerLat:'緯度', observerLon:'経度', observerSave:'保存',
  observerNaturalMode:'自然の空 · 現在地', observerTheatreMode:'任意 · NATURAL のみ', observerSetPrompt:'ほんとうの空には場所を設定', observerLocating:'現在地を確認中…',
  observerGeoFailed:'現在地を取得できない · 緯度と経度を入力してね', observerManualInvalid:'緯度 −90〜90、経度 −180〜180 を両方入力', observerSaveFailed:'場所を保存できない',
  observerManualSource:'手入力', observerGeoSource:'現在地', observerDefaultSource:'推定',
  saveSkyTitle:'わたしの空を保存', saveSkyHelp:'任意 · 保存しなくても遊べる。私用リンクをメールで受け取り、このブラウザで開いて1つのチャートを保存。',
  saveSkyEmail:'メール', saveSkyLink:'空のリンクをメール', saveSkySignOut:'サインアウト',
  saveSkyDate:'生年月日', saveSkyTime:'出生時刻', saveSkyUnknown:'時刻不明', saveSkyTz:'タイムゾーン',
  saveSkyPlace:'場所', saveSkyLat:'緯度', saveSkyLon:'経度', saveSkySubmit:'チャートを保存', saveSkyClear:'チャートを消去',
  saveSkyEdit:'チャートを編集', saveSkyNew:'新しいチャート', saveSkyCancelEdit:'キャンセル',
  saveSkyEpistemic:'象徴を学ぶためのメモで、予言ではない。出生情報は私用プロフィールにだけ保存され、きろくには入らない。',
  transitEssayButton:'今日の空のノート', transitEssayPending:'今日のノートを書いています…', transitEssayReady:'空のノートができました', transitEssayUnavailable:'ノートを用意できません · タップでもう一度',
  transitEssayWatchpoints:'注目するところ', transitEssayBack:'ポーズにもどる', transitEssayFallback:'象徴を学ぶためのノートで、予言ではない。',
  skyBriefTitle:'チャート + トランジット', skyBriefLoading:'データを用意しています…', skyBriefReady:'準備完了 · {date}', skyBriefUnavailable:'データを用意できません',
  skyBriefCopy:'データをコピー', skyBriefCopied:'データをコピーした', skyBriefShow:'データを表示', skyBriefHide:'データを隠す',
  skyBriefPrivate:'ネイタルとトランジットの生データ · 空のノートは上のボタン', skyBriefPreviewAria:'ネイタルと今日のトランジット', skyBriefCopyManual:'{keys} でコピーしてね',
  recordsHeader:'合唱のきろく', namePlaceholder:'きみの名前', loading:'読みこみ中…', clearLocal:'じぶんのベストを消す',
  nightCard:'夜のカード', cardSaveLabel:'絵をほぞん', cardCopied:'カードをコピーした', cardSaved:'カードをほぞんした', cardBlocked:'カードは ここに のこったよ',
  cardAria:'こんやの 夜のカード', cardDate:'{y}年{m}月{d}日',   // 日本語の日付は数字だけ — {mon}（英語の月の名前）は読まない
  shareEyebrow:'シェア · どのブラウザでも', shareTitleHtml:'夜を<span class="acc">シェア</span>',
  shareLedeHtml:'このリンクを送るだけ — ブラウザですぐ開く。インストール不要。<b>コードを読み取る</b>か、<b>リンクをコピー</b>してね。',
  qrAria:'このページへのQRコード', shareUrlAria:'シェア用リンク', copy:'コピー', back:'もどる',
  mobileDrag:'ドラッグ', mobileDragDesc:'まわして ねらう', mobileSend:'送る', mobileSendDesc:'こだまが光るうちに届ける', mobilePause:'ポーズ',
  coachP0:'月の糸をととのえて · 床が光ったら その文字を踏む', coachP0Progress:'踏めた {n}/{N} · 床の色に合わせて',
  coachP1:'あいだに送って · こだまが光るあいだにリンクを届ける', coachP1Mobile:'リンクを送って · 光るあいだに届けて',
  coachP1Progress:'声 {n}/{N} · 足もとも忘れずに', coachP1ProgressMobile:'声 {n}/{N} · 光る時に届けて',
  coachP2:'遠いこだまには早めに送る · 文字も踏みつづけて', coachP2Mobile:'遠いこだまには早めに送る · 先を読んで',
  coachP2Progress:'遠い声 {n}/{N} · つぎは満ちる夜', coachGraduate:'合唱はきみをおぼえた · 月先生が満ちる夜をひらく',
  fullNight:'満ちる夜', trainerToast:'月の糸のけいこ',
  bowMoon0:'新月', bowMoon1:'満ちる三日月', bowMoon2:'上弦の月', bowMoon3:'満ちる月', bowMoon4:'満月', bowMoon5:'欠ける月', bowMoon6:'下弦の月', bowMoon7:'欠ける三日月',
  bowLine0:'あすの夜 · {m}', bowLine1:'{m} が あすの夜を まっている', bowLine2:'また あした · {m}', bowLineFallback:'あすの夜も 空はここにある',
  bowDoneEyebrow:'この夜は おわり', bowNewNight:'はじめる — あたらしい夜',
  phasesEighth:'八つめの夜 · 月は そのすべてを 見ていた',
  rememberLine:'{n}夜が めぐった · {star} が きみの席を まもっていた', rememberAlone:'道場は きみの場所を あけて まっていた',
  ghostGiftMail:'きみは 手をのばした · {n}この音を つかまえた',
  // C3 chalk threshold strings: Japanese wording pending native review.
  ghostVisitorMail:'きみの音を {n}こ だれかが つかまえた · {sigil}', ghostVisitorBack:'手をのばしてくれた旅人が戸口にしるしを残した · {sigil}',
  ghostVisitorLine:'今夜の戸口には旅人のしるしがある · {sigil}',
  ghostPhaseLine:'このまえの{sigil}の夜がとなりを走る', ghostVisitorsLine:'今夜の戸口には{n}人の旅人のしるしがある · {sigils}',
  rememberAnchortaurus:'アルデバラン', rememberAnchorleo:'レグルス', rememberAnchorvirgo:'スピカ', rememberAnchorscorpius:'アンタレス',
  rememberFigaries:'おひつじ', rememberFigtaurus:'おうし', rememberFiggemini:'ふたご', rememberFigcancer:'かに', rememberFigleo:'しし', rememberFigvirgo:'おとめ', rememberFiglibra:'てんびん',
  rememberFigscorpius:'さそり', rememberFigophiuchus:'へびつかい', rememberFigsagittarius:'いて', rememberFigcapricornus:'やぎ', rememberFigaquarius:'みずがめ', rememberFigpisces:'うお',
  dealRule0:'やみが きいている', dealRule1:'風が うごきだす', dealRule2:'はやい声が めざめる', dealRule3:'風が おぼえている', dealRule4:'すべての合唱', dealRule5:'こだまは ふたつで こたえる', dealRule6:'遠い声が よぶ', dealRule7:'太鼓が やすむ',
  dealUpvenus:'金星が 出ている', dealUpjupiter:'木星が 出ている', dealUpmars:'火星が 出ている', dealUpsaturn:'土星が 出ている', dealUpmercury:'水星が 出ている',
  senseiEarlynear:'ちかいこだまに リンクが はやくとどく · むこうから 来るのを まって', senseiLatenear:'ちかいこだまに リンクが おそくとどく · もう そこにいるよ',
  senseiEarlymid:'なかほどのこだまに リンクが はやくとどく · ひといき ためてから', senseiLatemid:'なかほどのこだまに リンクが おそくとどく · ひといき はやく 送って',
  senseiEarlyfar:'遠いこだまに リンクが はやくとどく · いきを させてあげて', senseiLatefar:'遠いこだまに リンクが おそくとどく · 遠い声は もっと先に 送って',
  sensei2Mercy:'壁がひらく · なさけの一小節 · 息をして', sensei2Fill:'ドラムフィル · あわてず 言い切る',
  sensei2Bow:'構えを解けば 礼になる · 夜はみずから終わる', sensei2Star:'声がかえった · あの星はもう きみのもの',
  decoy:'声じゃない', decoySub:'そのまま見送って', faded:'きえた', fadedSub:'つぎの声を聞こう',
  tapPerfect:'ぴったり', tapAhead:'はやい ', tapBehind:'おそい ', skyFrozen:'空をとめた', skyResumed:'空がうごく', skyNaturalNoFreeze:'空はいまの時刻どおり', skyNoChart:'ほしの印はとどかない — 空は時をきざむ', skyMockChart:'ほしの印は みほん', lock:'ロック',
  skyListenDismiss:'空のノートを閉じる', skyListenDismissHint:'右クリック or X で閉じる',
  skyBlockedByEcho:'こだまが じゃま', skyNoMark:'そこには なにもない',   // 1.4: held-E gesture refusals. Both ≤14 glyphs — #ghostToast is nowrap (SPEC_MOON_CHORUS_UI §4)
  skyTempleKicker:'空の神殿', skyTempleHint:'発射でしらべる · Shift+E マウス解放（視点固定）· T で質問 · E で出る · ESC で一時停止', skyTempleGuide:'Shift+Eでこのパネル用にマウス解放（視点はそのまま）。Tで質問（チャート保存が必要）。全文はスクロール。', skyTempleEmpty:'空に照準を合わせてしらべる',
  skyTempleApplying:'接近中', skyTempleSeparating:'離反中', skyTempleNatal:'ネイタル', skyTempleRetro:'逆行', skyTempleEntered:'空の神殿', skyTempleExited:'道場にもどった', skyTempleResumed:'神殿にもどった',
  skyTempleFreeMouse:'マウス解放 · 視点ロック · HUD操作', skyTempleAimMouse:'照準にもどった', skyTempleControlsToast:'Shift+E マウス解放 · T 質問 · 発射でしらべる',
  chartTempleHint:'空の神殿で T（質問）を使うには、ここでサインインして出生チャートを保存。',
  skyChatAsk:'空にたずねる · T', skyChatInput:'この焦点についてたずねる…', skyChatInputAria:'空の焦点についてたずねる', skyChatSend:'送る', skyChatListening:'きいています…',
  skyChatUnavailable:'空のノートを用意できません', skyChatLimited:'今日はここまで · また明日', skyChatFailed:'空のノートを用意できません', skyChatNeedSignIn:'SAVE MY SKY でサインインすると質問できる', skyChatNeedChart:'出生チャートを保存すると質問できる', skyChatEpistemic:'象徴を学ぶためのメモ · 予言ではない · Tで質問 · Shift+Eでマウス解放 · Escで閉じる',
  pocketFocus:'びーとにのる', pocketLeanEarly:'はやめにのる', pocketSitBack:'おそめにのる',
  pocketLawOn:'のり · びーとまんなか', pocketLawEarly:'のり · はやめ', pocketLawLate:'のり · おそめ',
  pocketLawOnHelp:'床のピークもフリーズも まんなか', pocketLawEarlyHelp:'床のピークもフリーズも はやめ', pocketLawLateHelp:'床のピークもフリーズも おそめ',
  pocketLawLearning:'感じをきいている', pocketLawHearing:'きこえる', pocketLawSteady:'安定', pocketLawFeel:'感じ',
  pocketWithYou:'合ってる', pocketSoftFreeze:'やわいフリーズ', pocketLawMiss:'みす',
  pocketToastOn:'のり · びーとまんなか · フリーズはまんなか', pocketToastEarly:'のり · はやめ · フリーズもはやめ', pocketToastLate:'のり · おそめ · フリーズもおそめ',
  gamepad:'ゲームパッド', unmapped:'未対応', songMoonlight:'月光',
  resLow:'LOW ▸ タップでHIGH', resHigh:'HIGH ▸ タップでLOW', resForcedLow:'LOW固定 (保存済み)', resForcedHigh:'HIGH固定 (保存済み)', resAutoLow:'自動 → LOW', resAutoHigh:'自動 → HIGH',
  calibReady:'{n}回ぶん記録 — タップで自動設定', calibPlay:'W/A/S/D をビートに合わせて踏んでから、調整してね', calibNotEnough:'まだ足りない — もう少し踏んでから', calibApplied:'{avg}ms を {n}回から適用 → 合計 {total}ms',
  toneStartHtml:'<b>音が出なかった。</b>「はじめて」か「もう知ってる」をもういちど押してね。ダメならこのページの音のブロックを解除して。',
  tonePadHtml:'<b>音を出すには一度画面にさわってね。</b>クリックかタップのあと、「はじめて」か「もう知ってる」を選んでね（つづきはSTARTでも）。',
  toneFailedHtml:'<b>音を読みこめなかった。</b>通信か音のブロックを確かめて、「はじめて」か「もう知ってる」をもういちど押してね。',
  toneLoadingHtml:'<b>まだ音を読みこんでいるよ。</b>少し待って、「はじめて」か「もう知ってる」をもういちど押してね。',
  threeFailedHtml:'<b>星空を読みこめなかった。</b>通信かブロックを確かめて、ページを読みなおしてね。',
  yourBest:'じぶんのベスト · {time} · {bpm} bpm', boardOffline:'きろくに届かない ({status})', boardNetwork:'きろくに届かない — 通信エラー', boardEmpty:'まだ誰もいない — 最初の声になろう',
  peak:'さいこう', longest:'さいちょう', localCleared:'ベストを消した',
  pauseFullEyebrow:'ポーズ', pauseTrainEyebrow:'けいこ · ステップ{n}', pauseFullTitleHtml:'きき手の<span class="acc">きろく</span>', pauseTrainTitleHtml:'つづけて<span class="acc">きこう</span>',
  pauseFullLede:'<b>{song}</b> · {time} · さいこう <b>{bpm}</b> bpm', pauseTrainSteps:'けいこ · {time} · 踏めた <b>{n}/{N}</b>', pauseTrainVoices:'けいこ · {time} · 声 <b>{n}</b>',
  chipTime:'夜にいた時間', chipFinal:'さいごのBPM', chipPeak:'さいこうのBPM',
  saveSkyBothCoords:'緯度と経度を両方入れてね', saveSkySignedIn:'サインイン中', saveSkyLinked:'空をつないだ', saveSkySaved:'チャートを保存した',
  saveSkyNoChart:'サインイン中 · チャートなし', saveSkySavedLinked:'チャート保存 · 空をつないだ', saveSkySavedUnavailable:'チャート保存 · 私用の空に届かない',
  saveSkyCheckFields:'日付・時刻・タイムゾーン・場所を確認', saveSkyExpired:'空のリンクが期限切れ · もう一度サインイン', saveSkyLinkFailed:'空のリンクを送れなかった',
  saveSkyClearFailed:'チャートを消せなかった', saveSkyUnavailable:'私用の空に届かない', saveSkyChecking:'保存した空を確認中…', saveSkyNotConfigured:'わたしの空はまだ設定されていない',
  saveSkyNeedsWeb:'わたしの空は HTTP(S) が必要 · 遊ぶことはできる', saveSkyAuthUnavailable:'空のリンクに届かない · 遊ぶことはできる', saveSkyAuthLoading:'空のリンクを準備中…',
  saveSkySending:'私用の空リンクを送信中…', saveSkyCheckEmail:'メールを確認 · このブラウザで開いてね · 遊ぶことはできる', saveSkySaving:'チャートを保存中…', saveSkyClearing:'チャートを消去中…',
  saveSkyCleared:'チャートを消去した', saveSkySigningOut:'サインアウト中…', saveSkySignOutFailed:'サインアウトできなかった',
  saveSkyDecorative:'チャート保存 · デコレーションの空を使用中',
  copyOk:'コピーした', copyManual:'{keys} でコピーしてね', qrAlt:'{url} のQRコード'
};
(function(){
  try{
    var ja=LANG==='ja', J=window.JA;
    function txt(id,key){var e=document.getElementById(id);if(e)e.textContent=J[key];}
    function html(sel,key){var e=document.querySelector(sel);if(e)e.innerHTML=J[key];}
    function attr(id,name,key){var e=document.getElementById(id);if(e)e.setAttribute(name,J[key]);}
    if(ja){
      document.title=J.title;
      txt('speedLabel','drum'); txt('fireBtn','send'); attr('fireBtn','aria-label','sendAria'); attr('pauseBtn','aria-label','pauseAria'); attr('muteBtn','title','muteAria'); attr('muteBtn','aria-label','muteAria');
      txt('ovEyebrow','eyebrow'); html('#ovTitle','titleHtml'); html('#ovLede .lede-first','ledeFirstHtml'); html('#ovLede .lede-return','ledeReturn');
      txt('phonesText','phones'); txt('mouseDesc','mouseDesc'); txt('wasdDesc','wasdDesc'); txt('clickDesc','clickDesc'); txt('freezeDesc','freezeDesc'); txt('escDesc','escDesc');
      txt('selectDesc','selectDesc'); txt('templeEDesc','templeEDesc'); txt('templeFreeDesc','templeFreeDesc'); txt('templeTDesc','templeTDesc'); txt('chartTempleHint','chartTempleHint');
      txt('beatCircleLabel','beatCircleLabel');
      txt('modeQ','modeQ'); txt('beginTrainLabel','beginTrain'); txt('beginLabel','resume'); txt('recordsLabel','records'); txt('shareLabel','share');
      txt('resolutionLabel','resolution'); txt('offsetLabel','offset'); txt('calibLabel','calibrate'); txt('recordsHeader','recordsHeader'); attr('nameInput','placeholder','namePlaceholder'); txt('boardLoading','loading'); txt('clearLocalLabel','clearLocal');
      txt('nightCardLabel','nightCard'); txt('nightCardCopyLabel','copy'); txt('nightCardSaveLabel','cardSaveLabel'); attr('nightCardCv','aria-label','cardAria');   // NIGHT CARDS: the COPY label is the share modal's own word, reused rather than duplicated
      txt('playSettingsSummary','playSettingsSummary'); txt('skySettingsSummary','skySettingsSummary'); txt('chartSettingsSummary','chartSettingsSummary'); txt('helpSettingsSummary','helpSettingsSummary');
      txt('helpVerbsTitle','helpVerbsTitle'); txt('helpNightTitle','helpNightTitle'); txt('helpTankTitle','helpTankTitle'); txt('helpSkyTitle','helpSkyTitle'); txt('helpBowTitle','helpBowTitle');
      txt('helpDojoTitle','helpDojoTitle'); txt('helpTempleTitle','helpTempleTitle'); txt('helpChartTitle','helpChartTitle');
      html('#helpVerbsList','helpVerbsHtml'); html('#helpNightList','helpNightHtml'); html('#helpTankList','helpTankHtml'); html('#helpSkyList','helpSkyHtml'); html('#helpBowList','helpBowHtml');
      html('#helpDojoList','helpDojoHtml'); html('#helpTempleList','helpTempleHtml'); html('#helpChartList','helpChartHtml');   // whole-list swap: the HELP lists are the one place JA needs markup, not a label
      txt('observerLocationLabel','observerLocation'); txt('observerGeoLabel','observerGeo'); txt('observerLatLabel','observerLat'); txt('observerLonLabel','observerLon'); txt('observerSaveLabel','observerSave'); txt('observerLocationStatus','observerSetPrompt');
      txt('saveSkyTitle','saveSkyTitle'); txt('saveSkyHelp','saveSkyHelp'); txt('saveSkyEmailLabel','saveSkyEmail'); txt('saveSkyLinkLabel','saveSkyLink'); txt('saveSkySignOutLabel','saveSkySignOut');
      txt('saveSkyDateLabel','saveSkyDate'); txt('saveSkyTimeLabel','saveSkyTime'); txt('saveSkyUnknownLabel','saveSkyUnknown'); txt('saveSkyTzLabel','saveSkyTz'); txt('saveSkyPlaceLabel','saveSkyPlace'); txt('saveSkyLatLabel','saveSkyLat'); txt('saveSkyLonLabel','saveSkyLon'); txt('saveSkySubmitLabel','saveSkySubmit'); txt('saveSkyClearLabel','saveSkyClear');
      txt('saveSkyEditLabel','saveSkyEdit'); txt('saveSkyNewLabel','saveSkyNew'); txt('saveSkyCancelEditLabel','saveSkyCancelEdit'); txt('saveSkyEpistemic','saveSkyEpistemic');
      txt('transitEssayButtonLabel','transitEssayButton'); txt('transitEssayReaderEyebrow','transitEssayButton'); txt('transitEssayReaderWatchTitle','transitEssayWatchpoints'); txt('transitEssayReaderCloseLabel','transitEssayBack'); txt('transitEssayReaderEpistemic','transitEssayFallback');
      txt('skyBriefTitle','skyBriefTitle'); txt('skyBriefCopyLabel','skyBriefCopy'); txt('skyBriefToggleLabel','skyBriefShow'); txt('skyBriefPrivate','skyBriefPrivate'); attr('skyBriefPreview','aria-label','skyBriefPreviewAria');
      txt('skyTempleHint','skyTempleHint'); txt('skyTempleGuide','skyTempleGuide');
      txt('skyTempleChatAsk','skyChatAsk'); attr('skyTempleChatInput','placeholder','skyChatInput'); attr('skyTempleChatInput','aria-label','skyChatInputAria'); txt('skyTempleChatSend','skyChatSend'); txt('skyTempleChatEpistemic','skyChatEpistemic');
      txt('shareEyebrow','shareEyebrow'); html('#shareTitle','shareTitleHtml'); html('#shareLede','shareLedeHtml'); attr('qrcode','aria-label','qrAria'); attr('shareUrl','aria-label','shareUrlAria'); txt('copyBtn','copy'); txt('backLabel','back');
    }
    var touch=((navigator.maxTouchPoints||0)>0||('ontouchstart' in window))&&window.matchMedia('(pointer: coarse)').matches;
    if(touch){
      var lede=document.getElementById('ovLede'), keys=document.getElementById('keysRow');
      if(lede) lede.innerHTML=ja?J.ledeMobileHtml:'Send your rainbow link early enough to land while the Echo glows. Training starts with close Echoes and long blinks — no letters on touch.';
      if(keys) keys.innerHTML=ja
        ? '<span><b>'+J.mobileDrag+'</b>'+J.mobileDragDesc+'</span><span><b>'+J.mobileSend+'</b>'+J.mobileSendDesc+'</span><span><b>❙❙</b>'+J.mobilePause+'</span>'
        : '<span><b>DRAG</b>turn &amp; aim</span><span><b>SEND</b>land while the Echo glows</span><span><b>❙❙</b>pause</span>';
    }
  }finally{ document.documentElement.classList.remove('i18n-pending'); }
})();
         

                                            
                                    
                                     
                                   
                                      
                                                                                                                          
                                              
       
       
